EsteemedIO/esteemedio.github.io

- _includes/head.html
Update preview card of Esteemed website.
> EST-33: Update thumbnail image

- company.html
Updated Company Page Join team buttons to be links with mailto jobs@esteemed.io
> EST-40: Update Company Page Join team buttons

- company.html
Add subject and body to "Join Team" buttons from company page.
> EST-40: Add subject and body to join team buttons

- _config.yml
- _layouts/post.html
- blog.html
- categories.html
> replace /blogs

- _layouts/post.html
https://trello.com/c/DPy61n3f/65-reduce-the-desktop-container-size
> EST-65: Reduce blog container size

- schedule-demo.html
https://trello.com/c/pOXDqLK7/59-change-get-support-button-to-schedule-demo-button
Change the order of elements to be like this:
- page title, paragraph, calendar, then video title and video
> EST-59: Change order and updated spacing on Schedule Demo

- _layouts/author_index.html
> [EST-71] Fix issue with display related posts for single author

- _includes/footer.html
- contact.html
https://trello.com/c/xMu7QOKs/72-create-contact-us-page-with-form
> EST-72: Create contact page and add footer link for it

- _includes/footer.html
https://trello.com/c/UyOUHnuC/98-delete-redundant-form-on-contact-page
> [EST-98] Remove form on contact page

- _includes/footer.html
- privacy-policy.md
> [EST-113] Add phone number to footer

- _includes/footer.html
- _js/esteemed.js
- js/esteemed.js
> [EST-118] Fix working MC form when we use 2 forms on one page

- _layouts/post.html
> [EST-128] Remove author link for Press CT

- index.html
> Copy changes for site

- _includes/footer.html
- pages/resources/case-studies.html
> [EST-132] Hide Case studies from menu, add redirect to home

- _layouts/post.html
> [EST-135] Hide categories if empty

- _includes/head.html
> [EST-134] Remove HubSpot JavaScript from the site

- pages/about_us/careers.html
Changed copy for addition of buttons via Alex
> Updated for Bullhorn button addition

- _css/layout/_sections.scss
- _js/esteemed.js
- js/esteemed.js
- pages/404.html
- pages/about_us/about-us.html
- pages/about_us/careers.html
- pages/about_us/company.html
- pages/community.html
- pages/events.html
- pages/member-compensation-plan.html
- pages/news.html
- pages/partner-registration.html
- pages/products/esteemed-digital.html
- pages/products/for-agencies.html
- pages/products/for-brands.html
- pages/products/join-talent-network.html
- pages/products/products.html
- pages/products/solutions.html
- pages/products/xcontractors.html
- pages/resources/resources.html
- pages/service/agile-coaching.html
- pages/service/digital-delivery.html
- pages/service/discovery-planning.html
- pages/service/fractional-cto.html
- pages/service/project-management.html
- pages/service/services.html
- pages/service/technical-architecture.html
commit includes vendor directory with jekyll updates.
> Add Fade-In Transitions Sitewide

- _config.yml
> Change path without .html extensions

- _includes/footer.html
- pages/products/esteemed-digital.html
https://trello.com/c/5au2LaIM/157-create-form-for-esteemed-digital
> Add esteemed digital form

- pages/products/esteemed-digital.html
https://trello.com/c/4yr6DydU/155-add-cloud-hosting-pricing-to-esteemed-digital
> Add spacing and update links

- pages/service/fractional-cto.html
@albertvolkman  could you deploy it only on Dev site. Matt want to change text in this block before live.
> Add FAQ block to Fractional CTO page

- index.html
> Add fadein for the homepage

- pages/screening.html
> Remove screening team block

- pages/products/join-colleagues.html
https://trello.com/c/QQQhy7ZU/223-new-meta-data-for-join-colleagues
> Update meta join colleagues page

- _config.yml
- _includes/footer.html
- _includes/join-form.html
- _js/esteemed.js
- index.html
- js/esteemed.js
- pages/products/esteemed-digital.html
- pages/products/join-colleagues.html
- pages/screening.html
https://trello.com/c/9acPjbrB/210-capatcha-for-site-form
> Add recaptcha to the join form

- pages/404.html
https://trello.com/c/SzEGTOKY/261-odd-layout-on-404-page
> Fix 404 image

- _includes/join-form.html
- pages/products/join-colleagues.html
https://trello.com/c/YSyNUCgu/274-teardown-bh-form
> Replace BH form with button.

- _data/menus.yml
- _includes/footer.html
- pages/news.html
https://trello.com/c/izy0gy1P/273-delink-press-page-and-remove-references-to-it-redirecting-to-events-page
> [Est-273] Delink Press Page and remove references to it, redirecting
